#!/bin/bash
# ============================================
# Setup domain + HTTPS (Let's Encrypt)
# ============================================
# Usage:
#   ./setup-domain.sh                  # interactive prompt
#   ./setup-domain.sh builder.example.com  # pass domain as argument

set -e

# Determine docker compose command
if docker compose version &>/dev/null 2>&1; then
    COMPOSE="docker compose"
else
    COMPOSE="docker-compose"
fi

# Get domain
DOMAIN="${1}"
if [ -z "$DOMAIN" ]; then
    read -p "Enter your domain (e.g. builder.example.com): " DOMAIN
fi

if [ -z "$DOMAIN" ]; then
    echo "Error: domain is required"
    exit 1
fi

echo ""
echo "================================================"
echo "  Setting up HTTPS for: $DOMAIN"
echo "================================================"
echo ""

# --------------------------------------------------
# 1. Install certbot if missing
# --------------------------------------------------
if ! command -v certbot &>/dev/null; then
    echo "Installing Certbot..."
    if command -v amazon-linux-extras &>/dev/null; then
        sudo amazon-linux-extras install epel -y
        sudo yum install -y certbot
    elif command -v apt-get &>/dev/null; then
        sudo apt-get update && sudo apt-get install -y certbot
    else
        echo "Error: cannot install certbot — install it manually"
        exit 1
    fi
fi

# --------------------------------------------------
# 2. Stop nginx to free port 80
# --------------------------------------------------
echo "Stopping nginx container to free port 80..."
$COMPOSE stop nginx 2>/dev/null || true

# --------------------------------------------------
# 3. Get SSL certificate
# --------------------------------------------------
echo "Requesting SSL certificate from Let's Encrypt..."
sudo certbot certonly --standalone \
    --non-interactive --agree-tos \
    --register-unsafely-without-email \
    -d "$DOMAIN"

CERT_DIR="/etc/letsencrypt/live/$DOMAIN"

if [ ! -f "$CERT_DIR/fullchain.pem" ]; then
    echo "Error: certificate not found at $CERT_DIR"
    echo "Check certbot output above for details."
    exit 1
fi

echo "✅ Certificate obtained: $CERT_DIR"

# --------------------------------------------------
# 4. Generate nginx SSL config
# --------------------------------------------------
echo "Generating nginx config for $DOMAIN..."

CONF_FILE="nginx/conf.d/default.conf"

cat > "$CONF_FILE" <<NGINX
# Auto-generated by setup-domain.sh for $DOMAIN

upstream api_backend {
    server api:8000;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name $DOMAIN;

    ssl_certificate     /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # API proxy
    location /api/ {
        proxy_pass http://api_backend;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
    }

    # Uploaded files
    location /uploads/ {
        alias /app/uploads/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Published sites
    location /published/ {
        alias /app/published/;
        expires 1h;
        add_header Cache-Control "public";
    }

    # Frontend (SPA)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    # Static assets caching
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri =404;
    }
}
NGINX

echo "✅ Nginx config written to $CONF_FILE"

# --------------------------------------------------
# 5. Update docker-compose.prod.yml — add SSL volumes/ports
# --------------------------------------------------
echo "Updating docker-compose.prod.yml..."

# Check if letsencrypt volume already mounted
if ! grep -q "letsencrypt" docker-compose.prod.yml 2>/dev/null; then
    # Add SSL port and certificate volume to nginx service
    sed -i.bak '/^  nginx:/,/^  [a-z]/{
        /restart: always/a\
    ports:\
      - "80:80"\
      - "443:443"\
    volumes:\
      - /etc/letsencrypt:/etc/letsencrypt:ro
    }' docker-compose.prod.yml
    rm -f docker-compose.prod.yml.bak
    echo "✅ Added SSL ports and letsencrypt volume to docker-compose.prod.yml"
else
    echo "ℹ docker-compose.prod.yml already has letsencrypt config"
fi

# --------------------------------------------------
# 6. Update CORS in .env
# --------------------------------------------------
if [ -f .env ]; then
    # Add https domain to CORS if not already there
    if ! grep -q "$DOMAIN" .env; then
        sed -i.bak "s|CORS_ORIGINS=.*|CORS_ORIGINS=[\"https://$DOMAIN\",\"https://app.akm-advisor.com\"]|" .env
        rm -f .env.bak
        echo "✅ Updated CORS_ORIGINS in .env with https://$DOMAIN"
    fi
fi

# --------------------------------------------------
# 7. Rebuild and restart nginx
# --------------------------------------------------
echo "Rebuilding and starting services..."
$COMPOSE -f docker-compose.yml -f docker-compose.prod.yml up -d --build nginx

# --------------------------------------------------
# 8. Setup auto-renewal cron
# --------------------------------------------------
echo "Setting up certificate auto-renewal..."

CRON_CMD="0 3 1 */2 * certbot renew --pre-hook \"cd $(pwd) && $COMPOSE stop nginx\" --post-hook \"cd $(pwd) && $COMPOSE start nginx\""

# Add cron only if not already present
if ! sudo crontab -l 2>/dev/null | grep -q "certbot renew"; then
    (sudo crontab -l 2>/dev/null; echo "$CRON_CMD") | sudo crontab -
    echo "✅ Auto-renewal cron added (runs every 2 months)"
else
    echo "ℹ Auto-renewal cron already exists"
fi

echo ""
echo "================================================"
echo "  ✅ HTTPS setup complete!"
echo ""
echo "  https://$DOMAIN"
echo ""
echo "  Certificate:    $CERT_DIR"
echo "  Nginx config:   $CONF_FILE"
echo "  Auto-renewal:   cron every 2 months"
echo "================================================"
